MAX_TITLE_LENGTH = 200
MAX_CONTENT_LENGTH = 5000
MAX_SLIDES_PER_DECK = 20
MAX_BULLET_POINTS_PER_SLIDE = 10

SLIDE_WIDTH_INCHES = 13.333
SLIDE_HEIGHT_INCHES = 7.5

ACCENT_BAR_HEIGHT_EMU = 80000

FONT_NAME_DEFAULT = ""
FONT_SIZE_TITLE = 36
FONT_SIZE_SUBTITLE = 18
FONT_SIZE_BODY = 16
FONT_SIZE_HEADING = 24
FONT_SIZE_MAIN_TITLE = 48

GENERATED_FILENAME = "generated_slides.pptx"
