MAX_TITLE_LENGTH = 200
MAX_CONTENT_LENGTH = 5000
MAX_SLIDES_PER_DECK = 20
MAX_BULLET_POINTS_PER_SLIDE = 10

SLIDE_WIDTH_INCHES = 13.333
SLIDE_HEIGHT_INCHES = 7.5

ACCENT_BAR_HEIGHT_EMU = 80000

FONT_NAME_DEFAULT = ""
FONT_SIZE_TITLE = 32
FONT_SIZE_SUBTITLE = 20
FONT_SIZE_BODY = 22
FONT_SIZE_BULLET = 20
FONT_SIZE_HEADING = 24
FONT_SIZE_MAIN_TITLE = 44

GENERATED_FILENAME = "generated_slides.pptx"

PPTX_IMAGE_WIDTH_INCHES = 5.0
PPTX_IMAGE_HEIGHT_INCHES = 4.5
PPTX_IMAGE_LEFT_INCHES = 7.5
PPTX_IMAGE_TOP_INCHES = 1.8
PPTX_TEXT_WIDTH_WITH_IMAGE_INCHES = 6.0
PPTX_TEXT_WIDTH_DEFAULT_INCHES = 11.0

PPTX_CHART_WIDTH_INCHES = 5.5
PPTX_CHART_HEIGHT_INCHES = 4.0
PPTX_CHART_LEFT_INCHES = 7.0
PPTX_CHART_TOP_INCHES = 2.0

SUPPORTED_CHART_TYPES = ("column", "bar", "line", "pie")

GEMINI_MODEL_NAME = "gemini-2.5-flash"
IMAGEN_MODEL_NAME = "imagen-4.0-generate-001"

SLIDE_CATEGORIES = {
    "sales_proposal": "営業提案書",
    "business_plan": "事業企画書",
    "training": "研修資料",
    "report": "報告書",
}
DEFAULT_CATEGORY = "sales_proposal"

PREVIEW_WIDTH = 1920
PREVIEW_HEIGHT = 1080
PREVIEW_ACCENT_BAR = 6
PREVIEW_MARGIN_X = 120
PREVIEW_BULLET_INDENT = 40
PREVIEW_LINE_SPACING = 14
PREVIEW_ACCENT_LINE_W = 500
PREVIEW_TITLE_BLOCK_H = 300
PREVIEW_CONTENT_START_Y = 80
PREVIEW_MAX_TEXT_WIDTH = 1680

PREVIEW_FONT_DECK_TITLE = 72
PREVIEW_FONT_AUTHOR = 36
PREVIEW_FONT_SLIDE_TITLE = 48
PREVIEW_FONT_SUBTITLE = 28
PREVIEW_FONT_BODY = 28
PREVIEW_FONT_BULLET = 26
PREVIEW_FONT_BULLET_MARKER = 20
PREVIEW_FONT_PAGE_NUM = 24
